name: Train Model

on:
  push:
    paths:
      - 'train.py'
      - 'requirements.txt'
      - 'data/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run training script
      run: python train.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: model
        path: model/model.pkl
